FROM ruby:3.3.4

WORKDIR /app

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  yarn \
  postgresql-client \
  curl

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

CMD ["bash"]
